name: deploy
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  deploy_resume:
    runs-on: ubuntu-latest
    steps:
      - name: Notify build start
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.NOTIFY_WEBHOOK }}
          method: 'POST'
          data: '{ "content": "build started ${{ github.event.repository.name }}" }'
      - name: Setup repo
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Install Dependencies and build
        uses: actions/setup-node@v2
        # env:
          # PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
        with:
          args: install
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - run: npm run build
      # - name: build
      #   uses: mujo-code/puppeteer-headful@v2
      #   env:
      #     CI: 'true'
      #   with:
      #     args: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ secrets.DEPLOY_SOURCE_PATH }}
