name: deploy
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  deploy_resume:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Install Dependencies and build
        uses: actions/setup-node@v2
        with:
          args: install
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ secrets.DEPLOY_SOURCE_PATH }}
      - name: Release
        uses: actions/upload-artifact@v3
        with:
          name: resume pdf
          path: Anika\ Tahsin\ Chowdhury.pdf

