name: gh-page
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  deploy_gh_page:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
      - name: Find my ip
        id: findIp
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://ip.aljami.me/'
          method: 'GET'
          username: ${{ secrets.FIND_IP_USER }}
          password: ${{ secrets.FIND_IP_PASSWORD }}
      - name: Show Response
        run: echo ${{ steps.findIp.outputs.response }}