name: gh-page
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  deploy_gh_page:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public