name: gh-page
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  deploy_gh_page:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
      - name: Find my ip
        id: findIp
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://ip.aljami.me/'
          method: 'GET'
          username: ${{ secrets.FIND_IP_USER }}
          password: ${{ secrets.FIND_IP_PASSWORD }}
      - name: Print ip
        run: echo ${{ steps.findIp.outputs.response }}
      - name: copy file via ssh key
        uses: mdallasanta/ssh-scp-deploy@v1.0.4
        with:
          host: ${{ steps.findIp.outputs.response }}
          user: ${{ secrets.DEPLOY_USERNAME }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_KEY }}
          local: "./public"
          remote: ${{ secrets.DEPLOY_PATH }}
          pre_upload: echo "This will be executed before the upload!"
          post_upload: echo "This will be executed after the upload!"